//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HRM.FirstReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FirstServiceSoap", Namespace="http://tempuri.org/")]
    public partial class FirstService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FirstService() {
            this.Url = global::HRM.Properties.Settings.Default.HRM_FirstReference_FirstService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DataResult[] GetData(string from, string to, string makho) {
            object[] results = this.Invoke("GetData", new object[] {
                        from,
                        to,
                        makho});
            return ((DataResult[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(string from, string to, string makho) {
            this.GetDataAsync(from, to, makho, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(string from, string to, string makho, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        from,
                        to,
                        makho}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DataResult {
        
        private GetData khoField;
        
        private DMVT dmvtField;
        
        /// <remarks/>
        public GetData kho {
            get {
                return this.khoField;
            }
            set {
                this.khoField = value;
            }
        }
        
        /// <remarks/>
        public DMVT dmvt {
            get {
                return this.dmvtField;
            }
            set {
                this.dmvtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GetData {
        
        private System.Nullable<int> sttField;
        
        private string ma_khoField;
        
        private string ma_vtField;
        
        private string ten_vtField;
        
        private string ten_vt2Field;
        
        private string dvtField;
        
        private string nh_vt1Field;
        
        private string nh_vt2Field;
        
        private string nh_vt3Field;
        
        private string loai_vtField;
        
        private string ma_ntField;
        
        private System.Nullable<decimal> so_luongField;
        
        private System.Nullable<decimal> tienField;
        
        private System.Nullable<decimal> tien_ntField;
        
        private System.Nullable<decimal> sl_hopField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> stt {
            get {
                return this.sttField;
            }
            set {
                this.sttField = value;
            }
        }
        
        /// <remarks/>
        public string ma_kho {
            get {
                return this.ma_khoField;
            }
            set {
                this.ma_khoField = value;
            }
        }
        
        /// <remarks/>
        public string ma_vt {
            get {
                return this.ma_vtField;
            }
            set {
                this.ma_vtField = value;
            }
        }
        
        /// <remarks/>
        public string ten_vt {
            get {
                return this.ten_vtField;
            }
            set {
                this.ten_vtField = value;
            }
        }
        
        /// <remarks/>
        public string ten_vt2 {
            get {
                return this.ten_vt2Field;
            }
            set {
                this.ten_vt2Field = value;
            }
        }
        
        /// <remarks/>
        public string dvt {
            get {
                return this.dvtField;
            }
            set {
                this.dvtField = value;
            }
        }
        
        /// <remarks/>
        public string nh_vt1 {
            get {
                return this.nh_vt1Field;
            }
            set {
                this.nh_vt1Field = value;
            }
        }
        
        /// <remarks/>
        public string nh_vt2 {
            get {
                return this.nh_vt2Field;
            }
            set {
                this.nh_vt2Field = value;
            }
        }
        
        /// <remarks/>
        public string nh_vt3 {
            get {
                return this.nh_vt3Field;
            }
            set {
                this.nh_vt3Field = value;
            }
        }
        
        /// <remarks/>
        public string loai_vt {
            get {
                return this.loai_vtField;
            }
            set {
                this.loai_vtField = value;
            }
        }
        
        /// <remarks/>
        public string ma_nt {
            get {
                return this.ma_ntField;
            }
            set {
                this.ma_ntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> so_luong {
            get {
                return this.so_luongField;
            }
            set {
                this.so_luongField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> tien {
            get {
                return this.tienField;
            }
            set {
                this.tienField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> tien_nt {
            get {
                return this.tien_ntField;
            }
            set {
                this.tien_ntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> sl_hop {
            get {
                return this.sl_hopField;
            }
            set {
                this.sl_hopField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DMVT {
        
        private string ma_vtField;
        
        private string ten_vtField;
        
        private string ma_td1Field;
        
        private System.Nullable<decimal> sl_td1Field;
        
        private System.Nullable<decimal> packsField;
        
        private System.Nullable<decimal> tlcField;
        
        /// <remarks/>
        public string ma_vt {
            get {
                return this.ma_vtField;
            }
            set {
                this.ma_vtField = value;
            }
        }
        
        /// <remarks/>
        public string ten_vt {
            get {
                return this.ten_vtField;
            }
            set {
                this.ten_vtField = value;
            }
        }
        
        /// <remarks/>
        public string ma_td1 {
            get {
                return this.ma_td1Field;
            }
            set {
                this.ma_td1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> sl_td1 {
            get {
                return this.sl_td1Field;
            }
            set {
                this.sl_td1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> packs {
            get {
                return this.packsField;
            }
            set {
                this.packsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> tlc {
            get {
                return this.tlcField;
            }
            set {
                this.tlcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataResult[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591