//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSirvce_NS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FF35_Cord_appEntities : DbContext
    {
        public FF35_Cord_appEntities()
            : base("name=FF35_Cord_appEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int zcktkho_ReceiveSummary(Nullable<System.DateTime> dFrom, Nullable<System.DateTime> dTo, string cItem,
            string cCust, string cSite, string cJob, string cGroup, string cGroup2, string cGroup3, string cGroups, string cType, 
            string strTransCode, string strVoucherType, string strVoucherCode, string cisCalTransfer, string invFrom, string invTo, 
            string cUnit, Nullable<byte> nSize, string cForm, string cOrder, string strTable, string strJoin1, string strJoin2, 
            string strKey)
        {
            var dFromParameter = dFrom.HasValue ?
                new ObjectParameter("dFrom", dFrom) :
                new ObjectParameter("dFrom", typeof(System.DateTime));
    
            var dToParameter = dTo.HasValue ?
                new ObjectParameter("dTo", dTo) :
                new ObjectParameter("dTo", typeof(System.DateTime));
    
            var cItemParameter = cItem != null ?
                new ObjectParameter("cItem", cItem) :
                new ObjectParameter("cItem", typeof(string));
    
            var cCustParameter = cCust != null ?
                new ObjectParameter("cCust", cCust) :
                new ObjectParameter("cCust", typeof(string));
    
            var cSiteParameter = cSite != null ?
                new ObjectParameter("cSite", cSite) :
                new ObjectParameter("cSite", typeof(string));
    
            var cJobParameter = cJob != null ?
                new ObjectParameter("cJob", cJob) :
                new ObjectParameter("cJob", typeof(string));
    
            var cGroupParameter = cGroup != null ?
                new ObjectParameter("cGroup", cGroup) :
                new ObjectParameter("cGroup", typeof(string));
    
            var cGroup2Parameter = cGroup2 != null ?
                new ObjectParameter("cGroup2", cGroup2) :
                new ObjectParameter("cGroup2", typeof(string));
    
            var cGroup3Parameter = cGroup3 != null ?
                new ObjectParameter("cGroup3", cGroup3) :
                new ObjectParameter("cGroup3", typeof(string));
    
            var cGroupsParameter = cGroups != null ?
                new ObjectParameter("cGroups", cGroups) :
                new ObjectParameter("cGroups", typeof(string));
    
            var cTypeParameter = cType != null ?
                new ObjectParameter("cType", cType) :
                new ObjectParameter("cType", typeof(string));
    
            var strTransCodeParameter = strTransCode != null ?
                new ObjectParameter("strTransCode", strTransCode) :
                new ObjectParameter("strTransCode", typeof(string));
    
            var strVoucherTypeParameter = strVoucherType != null ?
                new ObjectParameter("strVoucherType", strVoucherType) :
                new ObjectParameter("strVoucherType", typeof(string));
    
            var strVoucherCodeParameter = strVoucherCode != null ?
                new ObjectParameter("strVoucherCode", strVoucherCode) :
                new ObjectParameter("strVoucherCode", typeof(string));
    
            var cisCalTransferParameter = cisCalTransfer != null ?
                new ObjectParameter("cisCalTransfer", cisCalTransfer) :
                new ObjectParameter("cisCalTransfer", typeof(string));
    
            var invFromParameter = invFrom != null ?
                new ObjectParameter("InvFrom", invFrom) :
                new ObjectParameter("InvFrom", typeof(string));
    
            var invToParameter = invTo != null ?
                new ObjectParameter("InvTo", invTo) :
                new ObjectParameter("InvTo", typeof(string));
    
            var cUnitParameter = cUnit != null ?
                new ObjectParameter("cUnit", cUnit) :
                new ObjectParameter("cUnit", typeof(string));
    
            var nSizeParameter = nSize.HasValue ?
                new ObjectParameter("nSize", nSize) :
                new ObjectParameter("nSize", typeof(byte));
    
            var cFormParameter = cForm != null ?
                new ObjectParameter("cForm", cForm) :
                new ObjectParameter("cForm", typeof(string));
    
            var cOrderParameter = cOrder != null ?
                new ObjectParameter("cOrder", cOrder) :
                new ObjectParameter("cOrder", typeof(string));
    
            var strTableParameter = strTable != null ?
                new ObjectParameter("strTable", strTable) :
                new ObjectParameter("strTable", typeof(string));
    
            var strJoin1Parameter = strJoin1 != null ?
                new ObjectParameter("strJoin1", strJoin1) :
                new ObjectParameter("strJoin1", typeof(string));
    
            var strJoin2Parameter = strJoin2 != null ?
                new ObjectParameter("strJoin2", strJoin2) :
                new ObjectParameter("strJoin2", typeof(string));
    
            var strKeyParameter = strKey != null ?
                new ObjectParameter("strKey", strKey) :
                new ObjectParameter("strKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zcktkho_ReceiveSummary", dFromParameter, dToParameter, cItemParameter, cCustParameter, cSiteParameter, cJobParameter, cGroupParameter, cGroup2Parameter, cGroup3Parameter, cGroupsParameter, cTypeParameter, strTransCodeParameter, strVoucherTypeParameter, strVoucherCodeParameter, cisCalTransferParameter, invFromParameter, invToParameter, cUnitParameter, nSizeParameter, cFormParameter, cOrderParameter, strTableParameter, strJoin1Parameter, strJoin2Parameter, strKeyParameter);
        }
    }
}
